const CARD_DATA = [
  {
    "id": "maj-00",
    "group": "major",
    "suit": null,
    "element": null,
    "numeral": "",
    "name": "Le Mat",
    "subtitle": null,
    "rank": null,
    "upright": "A fresh start, free movement, trust in the unknown and the soul that travels with no baggage."
  },
  {
    "id": "maj-01",
    "group": "major",
    "suit": null,
    "element": null,
    "numeral": "I",
    "name": "Le Bateleur",
    "subtitle": null,
    "rank": null,
    "upright": "A beginning, skill and focus, all the tools laid ready on the table."
  },
  {
    "id": "maj-02",
    "group": "major",
    "suit": null,
    "element": null,
    "numeral": "II",
    "name": "Junon",
    "subtitle": "paon",
    "rank": null,
    "upright": "Inner knowing, patience, the watchful queen, intuition that needs no proof and secrets held in quiet."
  },
  {
    "id": "maj-03",
    "group": "major",
    "suit": null,
    "element": null,
    "numeral": "III",
    "name": "L'Impératrice",
    "subtitle": null,
    "rank": null,
    "upright": "Abundance, creation, fertile ground, the making and nurturing of things."
  },
  {
    "id": "maj-04",
    "group": "major",
    "suit": null,
    "element": null,
    "numeral": "IIII",
    "name": "L'Empereur",
    "subtitle": null,
    "rank": null,
    "upright": "Structure, authority, solid ground and order built to last."
  },
  {
    "id": "maj-05",
    "group": "major",
    "suit": null,
    "element": null,
    "numeral": "V",
    "name": "Jupiter",
    "subtitle": "aigle",
    "rank": null,
    "upright": "Counsel from above, tradition, the teacher, belief and the higher view."
  },
  {
    "id": "maj-06",
    "group": "major",
    "suit": null,
    "element": null,
    "numeral": "VI",
    "name": "L'Amoureux",
    "subtitle": null,
    "rank": null,
    "upright": "A choice of the heart, union, the crossroads and what you truly value."
  },
  {
    "id": "maj-07",
    "group": "major",
    "suit": null,
    "element": null,
    "numeral": "VII",
    "name": "Le Chariot",
    "subtitle": null,
    "rank": null,
    "upright": "Forward motion, will, two forces held in hand and the journey taken on."
  },
  {
    "id": "maj-08",
    "group": "major",
    "suit": null,
    "element": null,
    "numeral": "VIII",
    "name": "La Justice",
    "subtitle": null,
    "rank": null,
    "upright": "Balance, truth, cause and effect, the fair weighing and accountability."
  },
  {
    "id": "maj-09",
    "group": "major",
    "suit": null,
    "element": null,
    "numeral": "VIIII",
    "name": "L'Ermite",
    "subtitle": null,
    "rank": null,
    "upright": "Withdrawal, the inner lamp, patient searching and wisdom found in quiet."
  },
  {
    "id": "maj-10",
    "group": "major",
    "suit": null,
    "element": null,
    "numeral": "X",
    "name": "La Roue de Fortune",
    "subtitle": null,
    "rank": null,
    "upright": "Turning, cycles, a change of fortune and the wheel that does not stop."
  },
  {
    "id": "maj-11",
    "group": "major",
    "suit": null,
    "element": null,
    "numeral": "XI",
    "name": "La Force",
    "subtitle": null,
    "rank": null,
    "upright": "Gentle power, the inner animal calmed, courage without violence and endurance."
  },
  {
    "id": "maj-12",
    "group": "major",
    "suit": null,
    "element": null,
    "numeral": "XII",
    "name": "Le Pendu",
    "subtitle": null,
    "rank": null,
    "upright": "Suspension, the willing pause, a new view from upside down and surrender that frees."
  },
  {
    "id": "maj-13",
    "group": "major",
    "suit": null,
    "element": null,
    "numeral": "XIII",
    "name": "Sans nom",
    "subtitle": "communément La Mort",
    "rank": null,
    "upright": "An ending that clears the ground, transformation and the cut that makes room."
  },
  {
    "id": "maj-14",
    "group": "major",
    "suit": null,
    "element": null,
    "numeral": "XIIII",
    "name": "Tempérance",
    "subtitle": null,
    "rank": null,
    "upright": "Blending, flow, healing, the right measure and opposites mixed with patience."
  },
  {
    "id": "maj-15",
    "group": "major",
    "suit": null,
    "element": null,
    "numeral": "XV",
    "name": "Le Diable",
    "subtitle": null,
    "rank": null,
    "upright": "Binding, desire, the material grip, what holds you and what you allow."
  },
  {
    "id": "maj-16",
    "group": "major",
    "suit": null,
    "element": null,
    "numeral": "XVI",
    "name": "La Maison Dieu",
    "subtitle": null,
    "rank": null,
    "upright": "A sudden break, the false structure falling, the shock that frees and lightning truth."
  },
  {
    "id": "maj-17",
    "group": "major",
    "suit": null,
    "element": null,
    "numeral": "XVII",
    "name": "L'Étoile",
    "subtitle": null,
    "rank": null,
    "upright": "Hope, renewal, the calm after the storm and gentle faith restored."
  },
  {
    "id": "maj-18",
    "group": "major",
    "suit": null,
    "element": null,
    "numeral": "XVIII",
    "name": "La Lune",
    "subtitle": null,
    "rank": null,
    "upright": "Dream and the hidden, what is not yet clear, intuition and illusion together and the night path."
  },
  {
    "id": "maj-19",
    "group": "major",
    "suit": null,
    "element": null,
    "numeral": "XVIIII",
    "name": "Le Soleil",
    "subtitle": null,
    "rank": null,
    "upright": "Clarity, warmth, plain joy and success seen in the open."
  },
  {
    "id": "maj-20",
    "group": "major",
    "suit": null,
    "element": null,
    "numeral": "XX",
    "name": "Le Jugement",
    "subtitle": null,
    "rank": null,
    "upright": "The call, awakening, rising to a new level, reckoning and renewal together."
  },
  {
    "id": "maj-21",
    "group": "major",
    "suit": null,
    "element": null,
    "numeral": "XXI",
    "name": "Le Monde",
    "subtitle": null,
    "rank": null,
    "upright": "Completion, wholeness, the circle closed, arrival and the four corners in their dance."
  },
  {
    "id": "batons-01",
    "group": "minor",
    "suit": "Bâtons",
    "element": "Feu",
    "numeral": "I",
    "name": "As de Bâtons",
    "subtitle": null,
    "rank": "As",
    "upright": "The pure spark of desire and will, a new fire lit, the offer of energy and beginning."
  },
  {
    "id": "batons-02",
    "group": "minor",
    "suit": "Bâtons",
    "element": "Feu",
    "numeral": "II",
    "name": "II de Bâtons",
    "subtitle": null,
    "rank": "II",
    "upright": "Desire meeting its first choice, two paths of action weighed, the will measuring where to go next."
  },
  {
    "id": "batons-03",
    "group": "minor",
    "suit": "Bâtons",
    "element": "Feu",
    "numeral": "III",
    "name": "III de Bâtons",
    "subtitle": null,
    "rank": "III",
    "upright": "Growth in work and will, the first result of effort, creative force beginning to answer back."
  },
  {
    "id": "batons-04",
    "group": "minor",
    "suit": "Bâtons",
    "element": "Feu",
    "numeral": "IIII",
    "name": "IIII de Bâtons",
    "subtitle": null,
    "rank": "IIII",
    "upright": "A stable fire, work given structure, a pause where desire has found ground to stand on."
  },
  {
    "id": "batons-05",
    "group": "minor",
    "suit": "Bâtons",
    "element": "Feu",
    "numeral": "V",
    "name": "V de Bâtons",
    "subtitle": null,
    "rank": "V",
    "upright": "Disruption in action and desire, effort meeting resistance, the spark tested by struggle."
  },
  {
    "id": "batons-06",
    "group": "minor",
    "suit": "Bâtons",
    "element": "Feu",
    "numeral": "VI",
    "name": "VI de Bâtons",
    "subtitle": null,
    "rank": "VI",
    "upright": "Fire moving onward with relief, work recognised, harmony restored through action taken."
  },
  {
    "id": "batons-07",
    "group": "minor",
    "suit": "Bâtons",
    "element": "Feu",
    "numeral": "VII",
    "name": "VII de Bâtons",
    "subtitle": null,
    "rank": "VII",
    "upright": "The will standing alone, effort under pressure, perseverance tested by the work itself."
  },
  {
    "id": "batons-08",
    "group": "minor",
    "suit": "Bâtons",
    "element": "Feu",
    "numeral": "VIII",
    "name": "VIII de Bâtons",
    "subtitle": null,
    "rank": "VIII",
    "upright": "Momentum in work and desire, swift action, mastery building through steady fire."
  },
  {
    "id": "batons-09",
    "group": "minor",
    "suit": "Bâtons",
    "element": "Feu",
    "numeral": "VIIII",
    "name": "VIIII de Bâtons",
    "subtitle": null,
    "rank": "VIIII",
    "upright": "The weight of fire near fullness, endurance under strain, desire close to its limit."
  },
  {
    "id": "batons-10",
    "group": "minor",
    "suit": "Bâtons",
    "element": "Feu",
    "numeral": "X",
    "name": "X de Bâtons",
    "subtitle": null,
    "rank": "X",
    "upright": "The full load of work and will, completion through effort, a cycle closed in heat and labour."
  },
  {
    "id": "batons-valet",
    "group": "minor",
    "suit": "Bâtons",
    "element": "Feu",
    "numeral": "",
    "name": "Valet de Bâtons",
    "subtitle": null,
    "rank": "Valet",
    "upright": "The young fire, a message of action, desire learning its first steps and testing its courage."
  },
  {
    "id": "batons-cavalier",
    "group": "minor",
    "suit": "Bâtons",
    "element": "Feu",
    "numeral": "",
    "name": "Cavalier de Bâtons",
    "subtitle": null,
    "rank": "Cavalier",
    "upright": "Fire in pursuit, action moving out to meet the world, drive with speed and appetite."
  },
  {
    "id": "batons-reine",
    "group": "minor",
    "suit": "Bâtons",
    "element": "Feu",
    "numeral": "",
    "name": "Reine de Bâtons",
    "subtitle": null,
    "rank": "Reine",
    "upright": "Mature fire held inwardly, creative will understood and tended, warmth that steadies others."
  },
  {
    "id": "batons-roi",
    "group": "minor",
    "suit": "Bâtons",
    "element": "Feu",
    "numeral": "",
    "name": "Roi de Bâtons",
    "subtitle": null,
    "rank": "Roi",
    "upright": "Mature fire shown outwardly, command of work and desire, authority that gives direction."
  },
  {
    "id": "coupes-01",
    "group": "minor",
    "suit": "Coupes",
    "element": "Eau",
    "numeral": "I",
    "name": "As de Coupes",
    "subtitle": null,
    "rank": "As",
    "upright": "The pure seed of feeling, a cup newly offered, love, intuition and connection beginning."
  },
  {
    "id": "coupes-02",
    "group": "minor",
    "suit": "Coupes",
    "element": "Eau",
    "numeral": "II",
    "name": "II de Coupes",
    "subtitle": null,
    "rank": "II",
    "upright": "Two cups meeting, feeling in balance, a first choice made through the heart."
  },
  {
    "id": "coupes-03",
    "group": "minor",
    "suit": "Coupes",
    "element": "Eau",
    "numeral": "III",
    "name": "III de Coupes",
    "subtitle": null,
    "rank": "III",
    "upright": "Feeling growing into shared form, connection bearing its first fruit, the heart answered by others."
  },
  {
    "id": "coupes-04",
    "group": "minor",
    "suit": "Coupes",
    "element": "Eau",
    "numeral": "IIII",
    "name": "IIII de Coupes",
    "subtitle": null,
    "rank": "IIII",
    "upright": "A stable pool of feeling, a pause in the heart, connection held and examined."
  },
  {
    "id": "coupes-05",
    "group": "minor",
    "suit": "Coupes",
    "element": "Eau",
    "numeral": "V",
    "name": "V de Coupes",
    "subtitle": null,
    "rank": "V",
    "upright": "Disruption in the realm of feeling, a loss or a grief, the cup spilled and what remains once it is mourned."
  },
  {
    "id": "coupes-06",
    "group": "minor",
    "suit": "Coupes",
    "element": "Eau",
    "numeral": "VI",
    "name": "VI de Coupes",
    "subtitle": null,
    "rank": "VI",
    "upright": "Harmony restored in feeling, kindness exchanged, the heart moving onward through memory and care."
  },
  {
    "id": "coupes-07",
    "group": "minor",
    "suit": "Coupes",
    "element": "Eau",
    "numeral": "VII",
    "name": "VII de Coupes",
    "subtitle": null,
    "rank": "VII",
    "upright": "The heart standing before many images, inner testing, desire reflected through dream and longing."
  },
  {
    "id": "coupes-08",
    "group": "minor",
    "suit": "Coupes",
    "element": "Eau",
    "numeral": "VIII",
    "name": "VIII de Coupes",
    "subtitle": null,
    "rank": "VIII",
    "upright": "Feeling in motion, mastery of the heart building, a steady leaving of what no longer answers."
  },
  {
    "id": "coupes-09",
    "group": "minor",
    "suit": "Coupes",
    "element": "Eau",
    "numeral": "VIIII",
    "name": "VIIII de Coupes",
    "subtitle": null,
    "rank": "VIIII",
    "upright": "The heart near fullness, feeling rich and intense, satisfaction close enough to be felt."
  },
  {
    "id": "coupes-10",
    "group": "minor",
    "suit": "Coupes",
    "element": "Eau",
    "numeral": "X",
    "name": "X de Coupes",
    "subtitle": null,
    "rank": "X",
    "upright": "The full load of feeling, completion in love and connection, the cycle closed in the heart."
  },
  {
    "id": "coupes-valet",
    "group": "minor",
    "suit": "Coupes",
    "element": "Eau",
    "numeral": "",
    "name": "Valet de Coupes",
    "subtitle": null,
    "rank": "Valet",
    "upright": "The young heart, a message of feeling, intuition learning its first language."
  },
  {
    "id": "coupes-cavalier",
    "group": "minor",
    "suit": "Coupes",
    "element": "Eau",
    "numeral": "",
    "name": "Cavalier de Coupes",
    "subtitle": null,
    "rank": "Cavalier",
    "upright": "Feeling in pursuit, the heart moving toward the world, love and intuition carried forward."
  },
  {
    "id": "coupes-reine",
    "group": "minor",
    "suit": "Coupes",
    "element": "Eau",
    "numeral": "",
    "name": "Reine de Coupes",
    "subtitle": null,
    "rank": "Reine",
    "upright": "The mature heart, feeling understood and held with care, depth offered to others, the one who nurtures by feeling."
  },
  {
    "id": "coupes-roi",
    "group": "minor",
    "suit": "Coupes",
    "element": "Eau",
    "numeral": "",
    "name": "Roi de Coupes",
    "subtitle": null,
    "rank": "Roi",
    "upright": "Mature feeling shown outwardly, command of the heart, steady authority in love and care."
  },
  {
    "id": "epees-01",
    "group": "minor",
    "suit": "Épées",
    "element": "Air",
    "numeral": "I",
    "name": "As de Épées",
    "subtitle": null,
    "rank": "As",
    "upright": "The pure seed of thought and truth, a clear word offered, the mind beginning its cut."
  },
  {
    "id": "epees-02",
    "group": "minor",
    "suit": "Épées",
    "element": "Air",
    "numeral": "II",
    "name": "II de Épées",
    "subtitle": null,
    "rank": "II",
    "upright": "Two thoughts held in tension, a choice of the mind, balance before the word is spoken."
  },
  {
    "id": "epees-03",
    "group": "minor",
    "suit": "Épées",
    "element": "Air",
    "numeral": "III",
    "name": "III de Épées",
    "subtitle": null,
    "rank": "III",
    "upright": "Thought reaching its first hard result, words that reveal pain, clarity with a cost."
  },
  {
    "id": "epees-04",
    "group": "minor",
    "suit": "Épées",
    "element": "Air",
    "numeral": "IIII",
    "name": "IIII de Épées",
    "subtitle": null,
    "rank": "IIII",
    "upright": "A stable pause in the mind, rest after conflict, thought held still long enough to settle."
  },
  {
    "id": "epees-05",
    "group": "minor",
    "suit": "Épées",
    "element": "Air",
    "numeral": "V",
    "name": "V de Épées",
    "subtitle": null,
    "rank": "V",
    "upright": "Disruption in truth and words, conflict in the mind, a victory that costs more than it gives."
  },
  {
    "id": "epees-06",
    "group": "minor",
    "suit": "Épées",
    "element": "Air",
    "numeral": "VI",
    "name": "VI de Épées",
    "subtitle": null,
    "rank": "VI",
    "upright": "The mind moving onward, relief after conflict, clarity carrying you toward calmer ground."
  },
  {
    "id": "epees-07",
    "group": "minor",
    "suit": "Épées",
    "element": "Air",
    "numeral": "VII",
    "name": "VII de Épées",
    "subtitle": null,
    "rank": "VII",
    "upright": "The mind standing alone, strategy or evasion, a test met by thought, working around rather than through."
  },
  {
    "id": "epees-08",
    "group": "minor",
    "suit": "Épées",
    "element": "Air",
    "numeral": "VIII",
    "name": "VIII de Épées",
    "subtitle": null,
    "rank": "VIII",
    "upright": "Momentum in thought, a pattern tightening, mastery building through a clear view of the bind."
  },
  {
    "id": "epees-09",
    "group": "minor",
    "suit": "Épées",
    "element": "Air",
    "numeral": "VIIII",
    "name": "VIIII de Épées",
    "subtitle": null,
    "rank": "VIIII",
    "upright": "The weight of the mind near fullness, worry intense and truth pressing hard in the dark."
  },
  {
    "id": "epees-10",
    "group": "minor",
    "suit": "Épées",
    "element": "Air",
    "numeral": "X",
    "name": "X de Épées",
    "subtitle": null,
    "rank": "X",
    "upright": "The full load of thought and conflict, a hard ending, the cycle closed by truth at its limit."
  },
  {
    "id": "epees-valet",
    "group": "minor",
    "suit": "Épées",
    "element": "Air",
    "numeral": "",
    "name": "Valet de Épées",
    "subtitle": null,
    "rank": "Valet",
    "upright": "The young mind, a message of truth, words learning their edge and first purpose."
  },
  {
    "id": "epees-cavalier",
    "group": "minor",
    "suit": "Épées",
    "element": "Air",
    "numeral": "",
    "name": "Cavalier de Épées",
    "subtitle": null,
    "rank": "Cavalier",
    "upright": "Thought in pursuit, truth moving out to meet the world, decision with speed and force."
  },
  {
    "id": "epees-reine",
    "group": "minor",
    "suit": "Épées",
    "element": "Air",
    "numeral": "",
    "name": "Reine de Épées",
    "subtitle": null,
    "rank": "Reine",
    "upright": "Mature thought held inwardly, truth understood with care, clarity that protects its own boundary."
  },
  {
    "id": "epees-roi",
    "group": "minor",
    "suit": "Épées",
    "element": "Air",
    "numeral": "",
    "name": "Roi de Épées",
    "subtitle": null,
    "rank": "Roi",
    "upright": "Mature thought shown outwardly, command of truth, authority through judgement and clear speech."
  },
  {
    "id": "deniers-01",
    "group": "minor",
    "suit": "Deniers",
    "element": "Terre",
    "numeral": "I",
    "name": "As de Deniers",
    "subtitle": null,
    "rank": "As",
    "upright": "The pure seed of the material world, a solid beginning, body, money or work offered in usable form."
  },
  {
    "id": "deniers-02",
    "group": "minor",
    "suit": "Deniers",
    "element": "Terre",
    "numeral": "II",
    "name": "II de Deniers",
    "subtitle": null,
    "rank": "II",
    "upright": "Two practical needs in balance, money, body or work held in careful motion."
  },
  {
    "id": "deniers-03",
    "group": "minor",
    "suit": "Deniers",
    "element": "Terre",
    "numeral": "III",
    "name": "III de Deniers",
    "subtitle": null,
    "rank": "III",
    "upright": "Material growth, the first visible result, work taking form through skill and cooperation."
  },
  {
    "id": "deniers-04",
    "group": "minor",
    "suit": "Deniers",
    "element": "Terre",
    "numeral": "IIII",
    "name": "IIII de Deniers",
    "subtitle": null,
    "rank": "IIII",
    "upright": "A stable hold in the material world, resources protected, a foundation kept in place."
  },
  {
    "id": "deniers-05",
    "group": "minor",
    "suit": "Deniers",
    "element": "Terre",
    "numeral": "V",
    "name": "V de Deniers",
    "subtitle": null,
    "rank": "V",
    "upright": "Disruption in the material world, strain in body, money or home, a practical loss felt plainly."
  },
  {
    "id": "deniers-06",
    "group": "minor",
    "suit": "Deniers",
    "element": "Terre",
    "numeral": "VI",
    "name": "VI de Deniers",
    "subtitle": null,
    "rank": "VI",
    "upright": "Harmony restored through exchange, resources shared, practical relief moving between hands."
  },
  {
    "id": "deniers-07",
    "group": "minor",
    "suit": "Deniers",
    "element": "Terre",
    "numeral": "VII",
    "name": "VII de Deniers",
    "subtitle": null,
    "rank": "VII",
    "upright": "The material test of patience, effort reviewed, work standing alone while results take shape."
  },
  {
    "id": "deniers-08",
    "group": "minor",
    "suit": "Deniers",
    "element": "Terre",
    "numeral": "VIII",
    "name": "VIII de Deniers",
    "subtitle": null,
    "rank": "VIII",
    "upright": "Momentum in work made solid, mastery building, steady labour shaping the material world."
  },
  {
    "id": "deniers-09",
    "group": "minor",
    "suit": "Deniers",
    "element": "Terre",
    "numeral": "VIIII",
    "name": "VIIII de Deniers",
    "subtitle": null,
    "rank": "VIIII",
    "upright": "The material world near fullness, comfort earned, body, home or money held with quiet strength."
  },
  {
    "id": "deniers-10",
    "group": "minor",
    "suit": "Deniers",
    "element": "Terre",
    "numeral": "X",
    "name": "X de Deniers",
    "subtitle": null,
    "rank": "X",
    "upright": "The full load of the material world, completion in home, body and wealth, the inheritance, the cycle closed in solid form."
  },
  {
    "id": "deniers-valet",
    "group": "minor",
    "suit": "Deniers",
    "element": "Terre",
    "numeral": "",
    "name": "Valet de Deniers",
    "subtitle": null,
    "rank": "Valet",
    "upright": "The young worker, a message of the material world, study and first steps in body, money or craft."
  },
  {
    "id": "deniers-cavalier",
    "group": "minor",
    "suit": "Deniers",
    "element": "Terre",
    "numeral": "",
    "name": "Cavalier de Deniers",
    "subtitle": null,
    "rank": "Cavalier",
    "upright": "The material mover, steady pursuit of work, health or money, progress through patient effort."
  },
  {
    "id": "deniers-reine",
    "group": "minor",
    "suit": "Deniers",
    "element": "Terre",
    "numeral": "",
    "name": "Reine de Deniers",
    "subtitle": null,
    "rank": "Reine",
    "upright": "Mature earth held inwardly, the body and home understood, care made practical and nourishing."
  },
  {
    "id": "deniers-roi",
    "group": "minor",
    "suit": "Deniers",
    "element": "Terre",
    "numeral": "",
    "name": "Roi de Deniers",
    "subtitle": null,
    "rank": "Roi",
    "upright": "Mature earth shown outwardly, command of work, money and home, authority made solid."
  }
];
